Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("shop.urls")),
    path("search/",include("search.urls")),
    path("cart/",include("cart.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name="cart"


urlpatterns=[
    path("add_cart/<int:p>",views.add_cart,name="add_cart"),
    path("cartview/",views.cartview,name="cartview"),
    path("itemless/<int:id>",views.cart_item_less,name="item_less"),
    path("cartremove/<int:id>",views.cart_remove,name="cart_remove"),
    path("orderform",views.orderform,name="orderform"),
    path("orderview",views.orderview,name="orderview"),
]

search/urls.py
from . import views
from django.urls import path
app_name="search"

urlpatterns=[

    path('',views.searchresult,name="searchresult")
]

shop/urls.py
from django.urls import path
from shop import views
app_name="shop"


urlpatterns=[
    path("",views.home,name="home"),
    path("allproducts/<slug:p>",views.product_detail,name="product_detail"),
    path("productdata/<slug:p>",views.products_data,name="products"),
    path('signup/',views.signup,name="signup"),
    path("login/",views.user_login,name="user_login"),
    path("logout/",views.user_logout,name="user_logout")

]

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

# Create your models here.
class Cart(models.Model):
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateField(auto_now_add=True)
    active=models.BooleanField(default=True)


    def __str__(self):
        return self.products.name

    def sub_total(self):
        return self.quantity*self.products.price

class Account(models.Model):
    account_no=models.CharField(max_length=20)
    account_type=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.account_no

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default='Pending')
    delivery_status=models.CharField(max_length=50,default='Pending')
    noofitems=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        self.user.username
    def sub_total(self):
        return self.noofitems*self.products.price

search/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from .models import Cart,Account,Order
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def cartview(request):
    total=0
    user=request.user
    try:
       product_detail=Cart.objects.filter(user=user)
       for i in product_detail:
           total+=i.quantity*i.products.price
    except CartDoesNotExist:
        Pass

    return render(request,"cart.html",{"product_details":product_detail,"total":total})
@login_required
def add_cart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity<cart.products.stock:
            cart.quantity+=1
            cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,products=product,quantity=1)
        cart.save()
    return redirect('cart:cartview')



@login_required
def cart_item_less(request,id):
    selected_item=Product.objects.get(id=id)
    user=request.user
    try:
        cart_item=Cart.objects.get(products=selected_item,user=user)
        if cart_item.quantity>1:
            cart_item.quantity-=1
            cart_item.save()
        else:
            cart_item.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')
@login_required
def cart_remove(request,id):
    selected_item=Product.objects.get(id=id)
    user=request.user
    try:
        cart_item=Cart.objects.get(products=selected_item,user=user)
        cart_item.delete()
    except:
        pass
    return redirect('cart:cartview')


@login_required
def orderform(request):
    total=0
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        ac=request.POST['ac']
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.products.price
        n=Account.objects.get(account_no=ac)
        if(n.amount>=total):
            n.amount=n.amount-total
            n.save()
            for i in cart:
                o=Order.objects.create(user=user,products=i.products,address=a,phone=p,order_status="Paid",noofitems=i.quantity)
                i.products.stock=i.products.stock-i.quantity
                i.products.save()
                o.save()
            cart.delete()
            msg="Order placed successfully"
            return render(request,"orderdetail.html",{'msg':msg,'total':total})
        else:
            msg="Insufficient Amount.You can't place order."
            return render(request,"orderdetail.html",{'msg':msg})
    return render(request,"orderform.html")

@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u,order_status="Paid")

    return render(request,"orderview.html",{'o':o,'name':u.username})

search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.
def searchresult(request):
    query=""
    products=None
    if(request.method=="POST"):
        query=request.POST.get('search_item')
        print(query)
        if(query):
            products=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'query':query,'products':products})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<style>
  .footer{
width:100%;
height:40px;
position:fixed;
padding:2px;
bottom:0px;
left:0px;
padding:10px;
margin:2px;
  background-color:#32612D;
  text-align:center;1
</style>
</head>
<body>
<div class="container-fluid">
    <center><img src="{% static 'image/logo.png' %}" height="90px" width="100px" alt="logo image"></center>
    <nav class="navbar navbar-expand-lg bg-success p-1">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online Store</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">Home</a>
        </li>
       {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Category
          </a>
          <ul class="dropdown-menu">
            {% for links in link %}
            <li><a class="dropdown-item" href="{% url 'shop:product_detail' links.slug %}">{{links.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping" style="font-size:20px;">{{item_count}}</i></a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:user_logout' %}">Logout</a>
        </li>
        {% else %}
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:signup' %}">Register</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:user_login' %}">Login</a>
        </li>
          {% endif %}
      </ul>

      <form class="d-flex" role="search" method="POST"   action="{% url 'search:searchresult' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search"  name="search_item"  placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</div>
{% block content %}
{% endblock %}
<footer class="footer" style="color:white;">
  <div>
    <p><i class="fa-regular fa-copyright"></i>Online store.All rights are reserved.</p>
    </div>
</footer>
</body>
</html>

templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid" style="margin-bottom:100px;">
    {% if not product_details %}
    <div>
        <h2 class="text-center">Cart is empty</h2>
        <center><strong><a href="{% url 'shop:home' %}">Continue Shopping</a></strong></center>
    </div>
    {% else %}
    <div class="row">
        <h2 class="text-center pt-1">SHOPPING CART</h2>
        <div class="col-sm-6">
            <table class="table table-bordered" >

                <tr>
                    <th colspan="5" class="text-center">Cart Items</th>
                    {% for item in product_details %}
                </tr>
                <tr>

                <td><img src="{{item.products.image.url}}" height="70px" width="70px"></td>
                    <td><strong>{{item.products.name}}</strong></td>
                <td><p><strong>Product id:</strong>{{item.products.id}}</p>
                <p><strong>Unit Price:</strong>{{item.products.price}}</p>
                <p><strong>Quantity:</strong>{{item.quantity}}*{{item.products.price}}</p></td>
                    <td>Total:{{item.sub_total}}</td>
                    <td>
                        {% if item.quantity < item.products.stock %}
                        <a href="{% url 'cart:add_cart' item.products.id %}"><i class="fa-solid fa-circle-plus"></i></a><br>
                        <a href="{% url 'cart:item_less' item.products.id %}"><i class="fa-sharp fa-solid fa-circle-minus"></i><br>
                        <a href="{% url 'cart:cart_remove' item.products.id %}"><i class="fa-solid fa-trash"></i></a>
                        {% else %}
                        <a href="{% url 'cart:item_less' item.products.id %}"><i class="fa-sharp fa-solid fa-circle-minus"></i></i></a><br>
                        <a href="{% url 'cart:cart_remove' item.products.id %}"><i class="fa-solid fa-trash"></i></a>
                        {% endif %}

                    </td>
                </tr>
              {% endfor %}
            </table>
        </div>
        <div class="col-sm-6"><table class="table table-bordered">
            <tr>
                <th colspan="5" class="text-center">Check out</th>
            </tr>
            <tr>
                <th class="text-center">Total Price:{{total}}</th>
            </tr>
        </table>
        <center>

            <a href="{% url 'shop:home' %}" class="btn btn-danger">Continue Shopping</a>
            <a href="{% url 'cart:orderform' %}" class="btn btn-danger">Place Order</a>

            </div>
        </center>

    </div>
    {% endif %}
{% endblock %}

templates/category.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
<img src="{% static 'image/shp.png' %}" style="height:500px;width:100%;" alt="logo image"></div>

<div class="container-fluid mt-3 mb-4" style="margin-bottom:100px;">
    <h2 class="text-center" style="color:red;">Our Collections</h2>
    <p style="text-align:center;color:blue;">Online store contains Watches, clothes, footwears, cosmetics, food items and all the electronic gadgets like Laptops Mobiles. We provide good quality products and we have delivery all over India without
    delivery charge.Online store is for someone who loves shopping</p>
</div>


<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for data in datas %}
        <div class="col-sm-4">
            <div class="card" >
                <img src="{{data.image.url}}" height="250px" width="80%" class="card-img-top" atl="..">
                <div class="card-body">
                    <h5 class="card-title text-center">{{data.name}}</h5>
                    <a href="{% url 'shop:product_detail' data.slug %}" class="btn btn-danger" style="position:relative;left:38%;">Products</a>
                 </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

 {% endblock %}

templates/login.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center text-danger mt-3">Login</h1>
<div class="container">

<form method="POST" class="shadow-none p-3 mb-4 bg-white rounded">
    {% csrf_token %}

<div class="mb-3 row">
  <label  class="col-sm-1 col-form-label mx-5">Username</label>
    <div class="col-sm-5">
  <input type="text" class="form-control" name="u">
        </div>
</div>

    <div class="mb-3 row ">
  <label  class="col-sm-1 col-form-label mx-5">Password</label>
        <div class="col-sm-5">
  <input type="password" class="form-control" name="p" >
            </div>
</div>

<div class="mb-3">
<center> <input type="submit" class="btn btn-danger" ></center>

</div>
</form>
    </div>
    {% if messages %}
    {% for i in messages %}
    <ul class="messages">
        <li>{{i}}</li>
    </ul>

</center>
{% endfor %}
{% endif %}


{% endblock %}

templates/orderdetail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container pt-3">
 <h2 class="text-center text-danger">{{msg}}</h2>
  <h5 class="text-center text-danger">Thank You...</h5>
  <p class="text-center"><a href="{% url 'shop:home' %}">Continue Shopping</a></p>
</div>

{% endblock %}

templates/orderform.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container pt-3">
    <form method="POST">
{% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="enter address">
</div>
<div class="mb-3">
  <label  class="form-label">Phone Number</label>
  <input class="form-control"  type="text" name="p" placeholder="enter phone number">
</div>
    <div class="mb-3">
  <label  class="form-label">Account Number</label>
  <input class="form-control"  type="text"  name="ac" placeholder="enter account number">
</div>
       <div class="mb-3">

  <center><input  type="submit" class="btn btn-danger"></center>
</div>

</form>
    </div>

{% endblock %}

templates/orderview.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container" style="maargin-bottom:100px;">
    <div class="row pt-3">
        <h4 class="text-center text-danger">Name of the Customer: {{name}}</h4>
        {% for i in o %}
        <div class="col-sm-5" style="border:2px solid red">
            <center><img src="{{i.products.image.url}}" height="150px" width="150px"></center>
        </div>
        <div class="col-sm-7 py-3 text-center" style="border:2px solid red">
            Delivery Address : {{i.address}}<br>
            Phone number : {{i.phone}}<br>
            {{i.products.name}}<br>
            Quantity Ordered:{{i.noofitems}}<br>
            Subtotal:{{i.sub_total}}<br>
            <strong class="text-primary">Ordered on {{i.date_added}}</strong><br>
            <strong class="text-danger">Delivery Status:{{i.delivery_status}}</strong>
        </div>
        {% endfor %}
    </div>
</div>




{% endblock %}

templates/product_details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid" >
    <center><img src="{{category_type.image.url}}"  class="mt-0"  alt="category image" style="width:100%;height:400px;"></center>
</div>
<div class="container-fluid text-center  pt-2" >
    <h2 class="text-danger">{{category_type.name}}</h2>
<p>{{category_type.description}}</p>
    </div>
<div class="container-fluid text-center">
    <div class="row">
        {% for products in product_datas %}
        <div class="col-sm-4">
            <div class="card mt-0 mb-5"   style="width:20rem;">
            <img src="{{products.image.url}}" style="height:200px;width:300px;"  class="card-img-top" alt="product image">
                <div class="card-body" style="">
            <h3 class="card-title text-center">{{products.name}}</h3>
            <p>{{products.description}}</p>
            <h5>Price:{{products.price}}</h5>
                    <div class="btn btn-danger">
                    <a href="{% url 'shop:products' products.slug %}"  style="color:white;text-decoration:none;">Details</a>
                        </div>
        </div>
    </div>
</div>


{% endfor %}

{% endblock %}

templates/products.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="card ms-3  mt-2" style="max-width:1000px;max-height:1000px;">
  <div class="row g-0">

    <div class="col-md-4">
        <img src="{{p_data.image.url}}" class="img-fluid rounded-start" height="250px" width="100%" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{p_data.name}}</h5>
        <p class="card-text">{{p_data.description}}</p>
        <p class="card-text"><small class="text-body-secondary">price:{{p_data.price}}</small></p>
      <p class="card-text"><small class="text-body-secondary">STOCK:{{p_data.stock}}</small></p
          <p class="card-text"><small class="text-body-secondary">Last updated:{{p_data.updated}}</small></p>
          {% if p_data.stock <= 0 %}
          <h2>Out of stock</h2>
          {% else %}
                    <a href="{% url 'cart:add_cart' p_data.id %}" class="btn btn-danger">Add to cart</a>

          {% endif %}
      </div>
    </div>

  </div>
</div>

{% endblock %}

templates/search.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div>
    <h5 class="text-center">You have searched for {{query}}</h5>
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <h6 class="text-center">SEARCH RESULT</h6>
    <div class="row">
        {% for i in products %}
        <div class="col-sm-4 mb-4">
            <div class="card text-center" style="">
                <img src="{{i.image.url}}" height="250px" width="100%" class="card-img-top" alt="image">
                <div class="card-body">
                    <h5 class="card-title text-center">{{i.name}}</h5>
                    <a href="{% url 'shop:products' i.slug %}" class="btn btn-danger" style="position:relative;">Product Details</a>
                </div>
            </div>
        </div>
        {% empty %}
        <h5 class="text-center text-danger">No result found</h5>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<center><h1>Signup</h1></center>
<center>
    <div class="container">
<form method="POST" >
    {% csrf_token %}

<div class="mb-2 row">
  <label  class="col-sm-1 col-form-label mx-2">Username</label>
    <div class="col-sm-5">
  <input type="text" class="form-control" name="u">
        </div>
</div>
    <div class="mb-2 row ">
  <label  class="col-sm-1 col-form-label mx-2">Password</label>
        <div class="col-sm-5">
  <input type="password" class="form-control" name="p" >
            </div>
</div>
    <div class="mb-2 row">
  <label  class="col-sm-1 col-form-label mx-2">Confirm Password</label>
        <div class="col-sm-5">
  <input type="password" class="form-control"  name="cp" >
            </div>
</div>
    <div class="mb-2 row">
  <label  class="col-sm-1 col-form-label mx-2">Email</label>
        <div class="col-sm-5">
  <input type="text" class="form-control"  name="e" >
            </div>
</div>

<div class="mb-2 row">
  <label  class="col-sm-1 col-form-label mx-2">Fist_name</label>
        <div class="col-sm-5">
  <input type="text" class="form-control"  name="f" >
            </div>
</div>

    <div class="mb-2 row">
  <label  class="col-sm-1 col-form-label mx-2">Last_name</label>
        <div class="col-sm-5">
  <input type="text" class="form-control"  name="l" >
            </div>
</div>

<div class="mb-4">
    <input type="submit" class="btn btn-primary ">

</div>
</form>
</div>
    {% if messages %}
    {% for i in messages %}
    <ul class="messages">
        <li>{{i}}</li>
    </ul>

</center>
{% endfor %}
{% endif %}
{% endblock %}